module Assembler
  ( assembler_main
  , assembler_msg
  ) where

import Assembler.Parser
import Assembler.Assembler

import System.Exit
import System.FilePath
import System.Console.GetOpt
import Control.Monad
import qualified Data.ByteString.Lazy as BS

data Flag = Parse
          | Assemble
          | Help
          deriving (Show, Eq, Read)

options :: [ OptDescr Flag ]
options
  = [ Option ['p'] ["parse"]    (NoArg Parse)
      "Outputs the abstract syntax tree generated by the parser."
    , Option ['a'] ["assemble"] (NoArg Assemble)
      "Outputs the assembled assembly in plain text."
    , Option []    ["help"]     (NoArg Help)
      "Prints this help message."
    ]

assembler_main :: [ String ] -> IO ()
assembler_main args = case getOpt Permute options args of
  (args, rp:fs,   []) -> if Help `elem` args
                           then putStrLn $ usageInfo header options
                           else do input <- readFile rp
                                   let parsed    = parse input
                                       assembled = assemble parsed
                                       binary    = assembleBinary parsed
                                   when (Parse `elem` args) $
                                     writeFile (replaceExtension rp ".ass_syn")
                                               (show parsed)
                                   when (Assemble `elem` args) $
                                     writeFile (replaceExtension rp ".assembled")
                                               (unlines . map show $ assembled)
                                   BS.writeFile (getWritePath rp fs) $
                                                BS.pack binary
  (   _,     _, errs) -> do putStrLn (concat errs ++ usageInfo header options)
                            exitWith (ExitFailure 1)

getWritePath :: String -> [ String ] -> FilePath
getWritePath _  (wp:[]) = wp
getWritePath rp _       = replaceExtension rp ".o"

header :: String
header = "Usage: " ++ assembler_msg

assembler_msg :: String
assembler_msg = "assemble [-a] read_path.asm [write_path.o]"
